version: "3.8"

services:
  db:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: automigrate
      POSTGRES_USER: automigrate
      POSTGRES_PASSWORD: automigrate

  # Database for testing

  test-postgres:
    image: postgres:14-alpine
    ports:
      - 5555:5432
    environment:
      POSTGRES_DB: automigrate
      POSTGRES_USER: automigrate
      POSTGRES_PASSWORD: automigrate
