version: "3.8"

services:
  check:
    image: abogoyavlensky/clojure-openjdk11-build:0.1.3
    volumes:
      - .:/app

  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: tuna
      POSTGRES_USER: tuna
      POSTGRES_PASSWORD: tuna

  adminer:
    image: adminer
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: db

  # For testing in CI

  test:
    image: abogoyavlensky/clojure-openjdk11-build:0.1.3
    depends_on:
      - test-postgres
    volumes:
      - .:/app

  #  databases for testing

  test-postgres:
    image: postgres
    ports:
      - 5555:5432
    environment:
      POSTGRES_DB: tuna
      POSTGRES_USER: tuna
      POSTGRES_PASSWORD: tuna
