version: "3.8"

services:
  check:
    image: abogoyavlensky/clojure-openjdk11-build:0.1.3
    volumes:
      - .:/app

  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: automigrate
      POSTGRES_USER: automigrate
      POSTGRES_PASSWORD: automigrate

  adminer:
    image: adminer
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: db

  # Database for testing

  test-postgres:
    image: postgres
    ports:
      - 5555:5432
    environment:
      POSTGRES_DB: automigrate
      POSTGRES_USER: automigrate
      POSTGRES_PASSWORD: automigrate

  # For testing in CI

  test:
    image: abogoyavlensky/clojure-openjdk11-build:0.1.3
    depends_on:
      - test-postgres
    environment:
      DATABASE_HOST_PORT: "test-postgres:5432"
    volumes:
      - .:/app

  # Build jar-file in CI

  build:
    image: abogoyavlensky/clojure-openjdk11-build:0.1.3
    environment:
      - CLOJARS_PASSWORD
      - CLOJARS_USERNAME
    volumes:
      - .:/app
