name: Install deps
runs:
  using: composite
  steps:
    - uses: jdx/mise-action@v2
    - name: Restore cached clojure dev deps
      uses: actions/cache/restore@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-clojure-dev-${{ hashFiles('**/deps.edn') }}
        restore-keys: ${{ runner.os }}-clojure-dev
