version: "3.8"

services:
  db:
    image: postgres:14-alpine
    ports:
      - 5333:5432
    environment:
      POSTGRES_DB: automigrate
      POSTGRES_USER: automigrate
      POSTGRES_PASSWORD: automigrate

  adminer:
    image: adminer
    ports:
      - 8081:8080
    environment:
      ADMINER_DEFAULT_SERVER: db

  clj:
    image: clojure:openjdk-11-tools-deps-1.10.3.1040-slim-buster
    volumes:
      - .:/app
