name: CI


on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Lint
        run: docker-compose run --rm check bash -c "make deps && make lint-init > /dev/null 2>&1 || true && make lint"

      - name: Fmt
        run: docker-compose run --rm check make fmt-check

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Test
        continue-on-error: true
        run: docker-compose run --rm test bash -c "make deps && make test"

      - name: ls
        run: ls -alh test/tuna/migrations

      - name: cat0
        run: cat test/tuna/migrations/0000_create_table_feed.edn

      - name: cat1
        run: cat test/tuna/migrations/0001_add_column_name.edn

      - name: cat2
        run: cat test/tuna/migrations/0002_add_column_name.edn
