name: Checks


on:
  push:
    branches: [ master ]

jobs:
  deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/cache-deps

  checks:
    needs: [ deps ]
    uses: ./.github/workflows/_checks.yaml

  deploy:
    runs-on: ubuntu-latest
    needs: [ checks ]
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - uses: ./.github/actions/restore-deps
      - name: Deploy Snapshot
        env:
          CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
          CLOJARS_PASSWORD: ${{ secrets.CLOJARS_PASSWORD }}
        run: make deploy-snapshot
