name: Checks


on:
  pull_request:
    branches: [ master ]

jobs:
  checks:
    uses: ./.github/workflows/_checks.yaml

  outdated:
    runs-on: ubuntu-latest
    needs: [ deps ]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/restore-deps
      - name: Outdated deps
        run: make outdated
