name: Release


on:
  push:
    tags:
      - "*"


jobs:
  deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/cache-deps

  checks:
    needs: [ deps ]
    uses: ./.github/workflows/_checks.yaml

#  deploy:
#    runs-on: ubuntu-latest
#    if: ${{ github.event.workflow_run.conclusion == 'success' }}
#    steps:
#      - uses: actions/checkout@v4
#      - uses: jdx/mise-action@v2
#      - name: Build jar-file and deploy to Clojars
#        run: make deploy-ci
#        env:
#          CLOJARS_PASSWORD: ${{secrets.CLOJARS_PASSWORD}}
#          CLOJARS_USERNAME: ${{secrets.CLOJARS_USERNAME}}
